### ISSUE TITLE
content: TODO

### ISSUE THREAD

**Issue by scarqin** [docschina/developer.chrome.com#10]
- [ ] Welcome
- [ ] What's new in Chrome extensions
- [ ] Getting started
- [ ] Welcome to Manifest V3
- [ ] Extensions platform vision
- [ ] Overview of Manifest V3
- [ ] Migrating to Manifest V3
- [ ] Manifest V3 migration checklist
- [ ] Manifest V2 support timeline
- [ ] What are extensions?
- [ ] What are themes?
- [ ] Frequently asked questions
- [ ] Extensions quality guidelines FAQ
- [ ] API Reference
- [ ] Samples
- [ ] Extension development overview
- [ ] Manifest file format
- [ ] Architecture overview
- [ ] Declare permissions
- [ ] Design the user interface
- [ ] Debugging extensions
- [ ] Samples
- [ ] Message passing
- [ ] Content scripts
- [ ] Manage events with service workers
- [ ] Match patterns
- [ ] Using promises
- [ ] Cross-origin isolation
- [ ] Cross-origin XMLHttpRequest
- [ ] Using eval in Chrome extensions
- [ ] Overriding Chrome settings
- [ ] Extending DevTools
- [ ] OAuth2: Authenticate users with Google
- [ ] Overriding Chrome pages
- [ ] Rich notifications API
- [ ] Migrating from background pages to service workers
- [ ] Protect user privacy
- [ ] Declare permissions and warn users
- [ ] Stay secure
- [ ] Accessibility (a11y)
- [ ] Localization message formats
- [ ] Give users options
- [ ] Extension hosting
- [ ] Alternative extension installation methods
- [ ] Installing extensions on Linux
- [ ] Tutorial: Google analytics
- [ ] About Manifest V2
- [ ] Getting started
- [ ] What are extensions?
- [ ] What are themes?
- [ ] Frequently asked questions
- [ ] Extension development overview
- [ ] Manifest file format
- [ ] Architecture overview
- [ ] Declare permissions
- [ ] Design the user interface
- [ ] Debugging extensions
- [ ] Samples
- [ ] Message passing
- [ ] Content scripts
- [ ] Manage events with background scripts
- [ ] Match patterns
- [ ] Cross-origin isolation
- [ ] Cross-origin XMLHttpRequest
- [ ] Using eval in Chrome extensions
- [ ] Overriding Chrome settings
- [ ] Extending DevTools
- [ ] OAuth2: Authenticate users with Google
- [ ] Overriding Chrome pages
- [ ] Rich notifications API
- [ ] Migrate to event-driven background scripts
- [ ] Protect user privacy
- [ ] Declare permissions and warn users
- [ ] Stay secure
- [ ] Accessibility (a11y)
- [ ] Localization message formats
- [ ] Give users options
- [ ] Chrome Web Store
- [ ] Alternative extension distribution options
- [ ] Installing extensions on Linux
- [ ] Tutorial: Google analytics

**Comment by Otto-J** [comment]
认领 Extensions platform vision 部分

**Comment by Yucohny** [comment]
认领 Frequently asked questions 部分

**Comment by Yucohny** [comment]
认领 Samples 部分

**Comment by Yucohny** [comment]
认领 Architecture overview 部分

**Comment by Yucohny** [comment]
认领 Cross-origin isolation 部分

**Comment by Yucohny** [comment]
认领 Extension hosting 部分
